"""empty message

Revision ID: 149a53fc8807
Revises: 2f960ef60144
Create Date: 2014-09-26 20:34:50.622000

"""

# revision identifiers, used by Alembic.
revision = '149a53fc8807'
down_revision = '2f960ef60144'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_reg', sa.Column('eat_date_day', sa.Integer(), nullable=True))
    op.add_column('food_reg', sa.Column('eat_date_month', sa.Integer(), nullable=True))
    op.add_column('food_reg', sa.Column('eat_date_year', sa.Integer(), nullable=True))
    op.drop_column('food_reg', 'eat_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_reg', sa.Column('eat_date', mysql.DATETIME(), nullable=True))
    op.drop_column('food_reg', 'eat_date_year')
    op.drop_column('food_reg', 'eat_date_month')
    op.drop_column('food_reg', 'eat_date_day')
    ### end Alembic commands ###
