"""empty message

Revision ID: 27efa042feba
Revises: 321593e168a7
Create Date: 2014-09-16 23:58:45.010000

"""

# revision identifiers, used by Alembic.
revision = '27efa042feba'
down_revision = '321593e168a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
