"""empty message

Revision ID: 288b31d84a4e
Revises: 149a53fc8807
Create Date: 2014-09-27 15:41:12.754000

"""

# revision identifiers, used by Alembic.
revision = '288b31d84a4e'
down_revision = '149a53fc8807'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rda', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('rda', sa.Column('gender', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rda', 'gender')
    op.drop_column('rda', 'age')
    ### end Alembic commands ###
