"""empty message

Revision ID: 2bdbd696e30e
Revises: 483fd41a5d13
Create Date: 2014-09-13 19:42:57.270000

"""

# revision identifiers, used by Alembic.
revision = '2bdbd696e30e'
down_revision = '483fd41a5d13'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'seq',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'seq',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default='0')
    ### end Alembic commands ###
