"""empty message

Revision ID: 2d576348595b
Revises: 32c1ab1e975
Create Date: 2014-09-12 23:35:30.053000

"""

# revision identifiers, used by Alembic.
revision = '2d576348595b'
down_revision = '32c1ab1e975'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
