"""empty message

Revision ID: 2f960ef60144
Revises: 3f8c50d9fc35
Create Date: 2014-09-26 20:31:05.904000

"""

# revision identifiers, used by Alembic.
revision = '2f960ef60144'
down_revision = '3f8c50d9fc35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
