"""empty message

Revision ID: 321593e168a7
Revises: 2bdbd696e30e
Create Date: 2014-09-14 23:52:04.670000

"""

# revision identifiers, used by Alembic.
revision = '321593e168a7'
down_revision = '2bdbd696e30e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'food_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'food_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###
