"""empty message

Revision ID: 32c1ab1e975
Revises: 35116b76fdba
Create Date: 2014-09-12 11:59:48.836000

"""

# revision identifiers, used by Alembic.
revision = '32c1ab1e975'
down_revision = '35116b76fdba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
