"""empty message

Revision ID: 35116b76fdba
Revises: 4b998509a3d1
Create Date: 2014-09-12 11:53:42.015000

"""

# revision identifiers, used by Alembic.
revision = '35116b76fdba'
down_revision = '4b998509a3d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
