"""empty message

Revision ID: 3f8c50d9fc35
Revises: 557b5320e906
Create Date: 2014-09-26 13:39:14.163000

"""

# revision identifiers, used by Alembic.
revision = '3f8c50d9fc35'
down_revision = '557b5320e906'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
