"""empty message

Revision ID: 46121ff64ed
Revises: 2d576348595b
Create Date: 2014-09-12 23:51:08.082000

"""

# revision identifiers, used by Alembic.
revision = '46121ff64ed'
down_revision = '2d576348595b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
