"""empty message

Revision ID: 483fd41a5d13
Revises: 575e0d1a6cd4
Create Date: 2014-09-13 00:12:06.227000

"""

# revision identifiers, used by Alembic.
revision = '483fd41a5d13'
down_revision = '575e0d1a6cd4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'seq',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'seq',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default='0')
    ### end Alembic commands ###
