"""empty message

Revision ID: 4b998509a3d1
Revises: db0506b1c6d
Create Date: 2014-09-12 08:32:47.860000

"""

# revision identifiers, used by Alembic.
revision = '4b998509a3d1'
down_revision = 'db0506b1c6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
