"""empty message

Revision ID: 52cfd0f46821
Revises: 288b31d84a4e
Create Date: 2014-09-28 00:21:21.853000

"""

# revision identifiers, used by Alembic.
revision = '52cfd0f46821'
down_revision = '288b31d84a4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
