"""empty message

Revision ID: 557b5320e906
Revises: 27efa042feba
Create Date: 2014-09-23 12:48:15.306000

"""

# revision identifiers, used by Alembic.
revision = '557b5320e906'
down_revision = '27efa042feba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
