"""empty message

Revision ID: 575e0d1a6cd4
Revises: 46121ff64ed
Create Date: 2014-09-13 00:09:37.407000

"""

# revision identifiers, used by Alembic.
revision = '575e0d1a6cd4'
down_revision = '46121ff64ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'food_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('food', 'seq',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'seq',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('food', 'food_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
