"""empty message

Revision ID: db0506b1c6d
Revises: None
Create Date: 2014-09-11 12:13:54.360000

"""

# revision identifiers, used by Alembic.
revision = 'db0506b1c6d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rda',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('na', sa.Integer(), nullable=True),
    sa.Column('sugar', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Integer(), nullable=True),
    sa.Column('sater_fat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('food',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('food_amount', sa.Integer(), nullable=True),
    sa.Column('food_cal', sa.Integer(), nullable=True),
    sa.Column('food_na', sa.Integer(), nullable=True),
    sa.Column('food_sugar', sa.Integer(), nullable=True),
    sa.Column('food_fat', sa.Integer(), nullable=True),
    sa.Column('food_satur', sa.Integer(), nullable=True),
    sa.Column('food_protein', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('user',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('rda_seq', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('user_pw', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rda_seq'], ['rda.seq'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('food_reg',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('user_seq', sa.Integer(), nullable=True),
    sa.Column('food_seq', sa.Integer(), nullable=True),
    sa.Column('eat_date', sa.DateTime(), nullable=True),
    sa.Column('eat_type', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_seq'], ['food.seq'], ),
    sa.ForeignKeyConstraint(['user_seq'], ['user.seq'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('result_an',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('user_seq', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_seq'], ['user.seq'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_an')
    op.drop_table('food_reg')
    op.drop_table('user')
    op.drop_table('food')
    op.drop_table('rda')
    ### end Alembic commands ###
